apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
   name: app-service
   app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
      type: mvc
    template: 
      metadata:
        name: app-pod
        labels:
            app: app
            type: mvc
        spec:
          containers:
            - name: app-pod
              image: fran556/apiutn:v1.0
              port:
                - containerPort: 8080
